name: Build and Push to Docker Hub

on:
  push:
    branches: [main]  # Only trigger on main branch pushes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx # modern Docker builder that supports multi-platform builds
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: Salmannazar007
          password: Nazar@1957 # It's recommended to use GitHub Secrets for sensitive data

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile  # change if your Dockerfile has a different name or path
          push: true
          tags: salmannazar007/mltest:latest,salmannazar007/mltest:${{ github.run_number }}
